### ISSUE TITLE
should the value of the scSEG index be low or high to consider that a gene is a stable expressed gene ?

### ISSUE THREAD

**Issue by aoumess** [SydneyBioX/scMerge#10]

**Comment by aoumess** [comment]
I've read your article (PNAS) and I'm not really sure to understand how to interpret the scSEG index. I've understood that the lower is the value of the index scSEG, the greater is the stability of the gene. Is that correct ?

**Comment by YingxinLin** [comment]
Hi,

A higher scSEG index indicates the gene is more likely to be stably expressed genes.

Yingxin

**Comment by kevinwang09** [comment]
Hi, 

The computational algorithm of scSEG is described in great details in this pre-print manuscript. 

Thank you
