### ISSUE TITLE
scMerge::sce_cbind error with method = "union"

### ISSUE THREAD

**Issue by zezhuo** [SydneyBioX/scMerge#16]
Hi scMerge team,

I got an error with sce_cbind function. data.list are seurat objects. I passed the counts matrix to a sce object to aggregate the data by scMerge. But I failed to combine the data from different batches using sce_cbind function. Any suggestions? Thanks!

Regards,
Nelson

```
> # Combine sce object
> data.list <- list(L07 = L07, L28 = L28, L30 = L30, L31 = L31, L43 = L43, L44 = L44)
> sce.list <- list()
> universe <- rownames(L07)
> 
> for (i in 1:length(data.list)){
+   sce.list[[i]] <- SingleCellExperiment(assays  = GetAssayData(data.list[[i]], slot = "counts"), colData = data.list[[i]]@meta.data)
+   assayNames(sce.list[[i]]) <- "counts"
+   colnames(sce.list[[i]]) <- paste(colnames(sce.list[[i]]), i, sep = "-")
+   # sizeFactors(sce.list[[i]]) <- colSums(assay(sce.list[[i]]))
+   # sce.list[[i]] <- scater::normalize(sce.list[[i]])
+ }
> 
> batch_name <- c("L07", "L28", "L30", "L31", "L43", "L44")
> names(sce.list) <- batch_name
> 
> # sce_cbind
> sce_binded <- scMerge::sce_cbind(sce.list, 
+                         method = "union",
+                         exprs = "counts",
+                         colData_names = c("orig.ident", "nCount_RNA", "nFeature_RNA", "percent.mt"),
+                         batch_names = batch_names)
The assay named 'counts' will be used to determine the proportion of zeroes for each batch
Error in mat[rownames(x), ] <- assay(x, exprs[i]) : 
  number of items to replace is not a multiple of replacement length
```

**Comment by zezhuo** [comment]
I get the answer. dgcMatrix is not supported by scMerge. as.matrix(assay(x)) is a possible way to deal with this error. Seurat is based on dgcMatrix, which saves the memory. 

It seems that scMerge is more friendly to small batches aggregation, saying smart-seq2. I failed to run scMerge on my laptop. Will try it on icloud later. 

Do you have any suggetions on big data set? Thanks!

Regards,
Nelson

```
> # Integration
> b6_scMerge <- scMerge::scMerge(
+   sce_combine = sce_binded, 
+   ctl = seg_symbol,
+   kmeansK = c(2, 5, 5, 5, 6, 3),
+   assay_name = "scMerge_unsupervised")
Error: cannot allocate vector of size 4.5 Gb
```

**Comment by kevinwang09** [comment]
Hi zezhuo, 
Thanks for letting us know that you have successfully diagnosed the problem. 
Yes, we did realise this issue and we are actively working on this [here](https://github.com/SydneyBioX/scMerge/tree/biocsing).

# Solution: 
If you want to avoid converting the data into the R `matrix` class, you can try out our latest version by installing from the `biocsing` branch, `BiocManager::install("SydneyBioX/scMerge", ref = "184756e11a4ec6fcece5d55ed53681d58a9b84b2")`. 

# A simple example based on scMerge function documentation

```
library(SummarizedExperiment)
library(scMerge)
library(Matrix)
###################### Identical to scMerge::scMerge vignette #####################
data('example_sce', package = 'scMerge')
data('segList_ensemblGeneID', package = 'scMerge')
sce_mESC <- scMerge(
    sce_combine = example_sce,
    ctl = segList_ensemblGeneID$mouse$mouse_scSEG,
    kmeansK = c(3, 3),
    assay_name = 'scMerge')
scater::plotPCA(sce_mESC, colour_by = 'cellTypes', shape = 'batch',
                run_args = list(exprs_values = 'logcounts'))
scater::plotPCA(sce_mESC, colour_by = 'cellTypes', shape = 'batch',
                run_args = list(exprs_values = 'scMerge'))


########### Modified example data ############################
example_sp = example_sce
## Assuming that the counts and logcounts slots are dgCMatrix
assay(example_sp, "counts") = as(assay(example_sce, "counts"), "dgCMatrix")
assay(example_sp, "logcounts") = as(assay(example_sce, "logcounts"), "dgCMatrix")

sce_mESC_sp <- scMerge(
  sce_combine = example_sp,
  ctl = segList_ensemblGeneID$mouse$mouse_scSEG,
  kmeansK = c(3, 3),
  assay_name = 'scMerge')
```

# Results
+ Based on my tests, scMerge is able to accept `matrix`, `dgCMatrix` and `HDF5Array` classes in the slots of a `SingleCellExperiment` object (except in the case where one of the slots is `matrix` and the other is `HDF5Array`). 
+ For the `dgCMatrix` class, you might save some RAM because sparse matrices are stored more efficiently, but RAM is still needed for the `scMerge` function computations. Without confirming the size of your data, I cannot guarantee that this computation won't still eat up your laptop's memory.
+ `HDF5Array` is good with out-of-RAM storage so you can save up more memory for the `scMerge` computation, but again, there are no guarantees. 
+ Just to give you an idea, I recently found that a data stored as 400MB in the RAM, took about 4GB RAM during the computations. 

Hopefully, that helps. 
Thanks, 
Kevin

**Comment by kevinwang09** [comment]
Hi zezhuo, 
Thanks for letting us know that you have successfully diagnosed the problem. 
Yes, we did realise this issue and we are actively working on this [here](https://github.com/SydneyBioX/scMerge/tree/biocsing). Please allow us a few days to work on this problem. 

If you are happy to use HDF5Array out of memory computations, you are welcome to try 

```
BiocManager::install("SydneyBioX/scMerge", ref = "184756e11a4ec6fcece5d55ed53681d58a9b84b2")
library(SummarizedExperiment)
library(scMerge)
library(Matrix)
###################### Identical to scMerge::scMerge vignette #####################
data('example_sce', package = 'scMerge')
data('segList_ensemblGeneID', package = 'scMerge')
profvis::profvis({
  sce_mESC <- scMerge(
    sce_combine = example_sce,
    ctl = segList_ensemblGeneID$mouse$mouse_scSEG,
    kmeansK = c(3, 3),
    assay_name = 'scMerge')
})
scater::plotPCA(sce_mESC, colour_by = 'cellTypes', shape = 'batch',
                run_args = list(exprs_values = 'logcounts'))
scater::plotPCA(sce_mESC, colour_by = 'cellTypes', shape = 'batch',
                run_args = list(exprs_values = 'scMerge'))


#######################################
example_hd = example_sce
## Assuming that the counts and logcounts slots are HDF5Array
assay(example_hd, "counts") = as(assay(example_sce, "counts"), "HDF5Array")
assay(example_hd, "logcounts") = as(assay(example_sce, "logcounts"), "HDF5Array")

profvis::profvis({
  sce_mESC_hd <- scMerge(
    sce_combine = example_hd,
    ctl = segList_ensemblGeneID$mouse$mouse_scSEG,
    kmeansK = c(3, 3),
    assay_name = 'scMerge')
})
```

Thanks
Kevin

**Comment by zezhuo** [comment]
Hi Kevin, 

I have successfully integrated the data by scMerge. Then I pass the assay(scMerge, "scMerge_unsupervised") matrix to Seurat for follow up analyses, including scale data and runPCA again. Does it make sence for your output matrix?

Regards,
Nelson

**Comment by zezhuo** [comment]
> 
> 
> Hi zezhuo,
> I am not sure what do you mean by scale data. But running PCA is for visualisation purpose is definitely okay.
> Thanks,
> Kevin

Hi @kevinwang09 ,

I rescaled the data to 
> Shifts the expression of each gene, so that the mean expression across cells is 0;
> Scales the expression of each gene, so that the variance across cells is 1.
for clustering and running the PCA for visuallization.

In addition, I would like find marker genes of each cluster. For finding marker genes, do you recommend the assay(scMerge, "scMerge_unsupervised") matrix? or the raw counts matrix without correction?

Regards,
Nelosn

**Comment by kevinwang09** [comment]
Hi Nelson, 
Scaling the data for visualisation purpose should be okay. 
As for marker discovery, it is a choice. You could work with the raw counts matrix if you choose to (after which you can run scMerge and supply the clustered cell types), or you can run marker discovery on the assay(scMerge, "scMerge_unsupervised") matrix. In the latter case, @YingxinLin can make a recommendation on a pipeline. 
Thanks, 
Kevin
