### ISSUE TITLE
Request for a detailed vignette for beginners to try scMerge

### ISSUE THREAD

**Issue by mzhibo** [SydneyBioX/scMerge#24]
Hi,
Thanks for developing such a great tool! I am interested in integrating multiple datasets from different stages and conditions. Your scMerge supports further pseudotime trajectory inference which is great!
I am wondering if you could add a more detailed vignette for beginners (or people that mainly use seurat or monocles) to quickly try your tool. Like myself, I am not very familiar with SingleCellExperiment object. 
Since you know the tool best, It will be great if you could include in your vignette about how to start from a raw count matrix or a expression level (tpm) matrix, and do scMerge, and what would be recommended practice if we are interested in further analysis with monocle3 and seurat3.
Thank you for considering!
Best,
Zhibo

**Comment by kevinwang09** [comment]
Hi, 
It sounds like you are already familiar with `monocle`, so I will try to use that as an example.

A SCE object is very similar to a `CellDataSet` object in `monocle`.  In `SCE`, the main slots are
+ `assays`: a `list` where you can store expression matrix information. Rows are genes and columns are cells.
+ `rowData`: a `data.frame` or `DataFrame` where you can store information about the genes.
+ `colData`:  a `data.frame` or `DataFrame` where you can store information about the cells.

These three slots are roughly correspond to `cellData`, `featureData` and `phenoData` in a `CellDataSet` object. 




Consider the example below:
```
library(SingleCellExperiment)
set.seed(123)
ncells = 20
ngenes = 100
y = matrix(rpois(ncells*ngenes, lambda = 1), ncol = ncells)

rowData = data.frame(
  gene_short_name = paste0("gene", 1:ngenes))

colData = data.frame(
  batch = sample(LETTERS[1:4], ncol(y), replace = TRUE),
  cell_type = sample(LETTERS, ncol(y), replace = TRUE))

sce = SingleCellExperiment(
  assays = list(counts = y),
  rowData = rowData,
  colData = colData)


library(monocle)
cds = newCellDataSet(
  cellData = y,
  featureData = AnnotatedDataFrame(rowData),
  phenoData = AnnotatedDataFrame(colData))
```

**Comment by mzhibo** [comment]
Thanks for the illustration!
