### ISSUE TITLE
Selecting all cells : replicate_prop = 1

### ISSUE THREAD

**Issue by CodeInTheSkies** [SydneyBioX/scMerge#30]
Hi there,

In this portion of your vignette, 
http://bioconductor.org/packages/release/bioc/vignettes/scMerge/inst/doc/scMerge.html#selecting-all-cells

you describe about selecting all cells for kMeans clustering.  And the difference between this code and the previous default code seems to be `replicate_prop = 1`.  Is this right?  But then, in the help pages of "scMerge", the default of this parameter seems to be set to 1 anyway.  So, effectively, that indicates that by default, all the cells are anyway selected?

Can you please clarify?

Thank you!

**Comment by nick-robo** [comment]
This has been addressed in scMerge2
