### ISSUE TITLE
how to prepare the input data form a Seurat object

### ISSUE THREAD

**Issue by xinmiaoyan** [SydneyBioX/scMerge#36]
this is a great tool, and I'd like try it to so some fancy analysis, but I'm not familiar with the input data, so how do I prepare it from a Seurat object, appreciate your response.

**Comment by Billsfriend** [comment]
I am not sure if this is the right way, but it worked without error for me.
First ensure your Seurat object has gone through `NormalizeData()`, then use `as.SingleCellExperiment()` will convert it to a acceptable input for `scMerge()`.
