### ISSUE TITLE
Atlas level integration

### ISSUE THREAD

**Issue by ConDem94** [SydneyBioX/scMerge#38]
Hi, where can I find the vignette for atlas level integration of multiple studies, platforms etc? 

Also, does scMerge2 perform well for integrating single-cell and single-nucleus datasets together?

Thank you!

Best wishes,
Constantinos

**Comment by YingxinLin** [comment]
Dear Constantinos,

Thank you for your interest in scMerge2. Please find the vignette of scMerge2 in this link: https://sydneybiox.github.io/scMerge/articles/scMerge2.html as well as a workshop tutorial in https://yingxinlin.github.io/scMergeBioc2023/articles/an_intro_to_scMerge2.html

We tested the scMerge2 in integrating single-cell and single-nucleus datasets from MOp before and it performs well.

Best wishes,
Yingxin
