### ISSUE TITLE
Bioconductor support

### ISSUE THREAD

**Issue by robertamezquita** [SydneyBioX/scMerge#5]
Hi, I was wondering if there are plans to submit this package to Bioconductor?

**Comment by kevinwang09** [comment]
Hi, yes, we are actively working on the scMerge package to make sure it meets the standards of Bioconductor. Thanks.

On 22 Jan 2019, at 6:55 am, Robert Anthony Amezquita <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I was wondering if there are plans to submit this package to Bioconductor?

**Comment by kevinwang09** [comment]
Hi, scMerge is now on Bioconductor. Thank you for your suggestion! 
https://bioconductor.org/packages/scMerge
