### ISSUE TITLE
Cannot download processed data in the Case Study page

### ISSUE THREAD

**Issue by genecell** [SydneyBioX/scMerge#7]
Hi,

I would like to check the integrated data in the Case Study page, but found the link not available, for example:
```
Not Found
The requested URL /u/yingxinl/wwwnb/scMergeData/mESC_scMerge.rds was not found on this server.
```
Beside, is there any available links for users to download the input data as RData formats?

Thanks in advance,
BP

**Comment by kevinwang09** [comment]
Hi BP, 
1. The mESC_scMerge.rds file is now up online again. This should contain the merged dataset. 
2. The raw input data is here (https://github.com/SydneyBioX/scMerge.data/tree/master/data). We will upload this to the same server in the coming days. 

Thanks!
Kevin

**Comment by genecell** [comment]
Dear Kevin,

Than you for your rapid reply!
Will other raw input data, other than mESC, also be available in future? Thank you!

Best regards,
BP

**Comment by kevinwang09** [comment]
Hi BP, 
At this point in time, we do not have plans to release our data as RData files. However, every dataset that we have used in our case study are from public repositories and documented in our website. e.g. the Mouse ESC data is from ArrayExpress E-MTAB-2600. 

Thanks, 
Kevin

**Comment by genecell** [comment]
Dear Kevin,

No problem. Thank you for your warm reply!
Ideas behind scMerge are really impressive!

Best regards,
BP

**Comment by kevinwang09** [comment]
Thanks!
