### ISSUE TITLE
Using BiocSingular for SVD operations

### ISSUE THREAD

**Issue by kevinwang09** [SydneyBioX/scMerge#8]
BiocSingular is officially available in BioC 3.9 release. This package should help with managing different SVD operations. 

https://bioconductor.org/packages/release/bioc/html/BiocSingular.html

This is a package that we should potentially use for consistencies.

**Comment by nick-robo** [comment]
@YingxinLin is this planned?

**Comment by YingxinLin** [comment]
It is implemented in scMerge2 now.
